version: "3"
services:
  # feedvault:
  #   container_name: feedvault
  #   image: ghcr.io/thelovinator1/feedvault:latest
  #   user: "1000:1000"
  #   restart: always
  #   environment:
  #     - DEBUG=False
  #     - SECRET_KEY=${SECRET_KEY}
  #     - DB_NAME=feedvault
  #     - DB_USER=feedvault
  #     - DB_PASSWORD=${DB_PASSWORD}
  #     - DB_HOST=feedvault_postgres
  #     - DB_PORT=5432
  #     - REDIS_PASSWORD=${REDIS_PASSWORD}
  #     - REDIS_PORT=6379
  #     - REDIS_HOST=garnet
  #   volumes:
  #     - /Docker/FeedVault/FeedVault/staticfiles:/app/staticfiles
  #     - /mnt/Fourteen/Docker/FeedVault/media:/app/media
  garnet:
    container_name: garnet
    image: "ghcr.io/microsoft/garnet"
    user: "1000:1000"
    restart: always
    ulimits:
      memlock: -1
    command: ["--auth", "Password", "--password", "${REDIS_PASSWORD}"]
    ports:
      - "6379:6379"
    volumes:
      - /Docker/FeedVault/Garnet:/data
